export const types = {
  UPDATE_NAVIGATION_DATA: 'UPDATE_NAVIGATION_DATA',
  UPDATE_SLIDER_DATA: 'UPDATE_SLIDER_DATA',
  UPDATE_MEMBER_DATA: 'UPDATE_MEMBER_DATA',
  UPDATE_BANNER_DATA: 'UPDATE_BANNER_DATA',
  UPDATE_ADMISSION_DATA: 'UPDATE_ADMISSION_DATA',
  UPDATE_CONTENT_DATA: 'UPDATE_CONTENT_DATA',
  UPDATE_LOGIN_STATUS: 'UPDATE_LOGIN_STATUS',
  UPDATE_NEWS_DATA: 'UPDATE_NEWS_DATA'
}
